export const REPOSITORIO_USUARIOS = Symbol('REPOSITORIO_USUARIOS');
export const REPOSITORIO_BICICLETAS = Symbol('REPOSITORIO_BICICLETAS');
export const REPOSITORIO_RESERVAS = Symbol('REPOSITORIO_RESERVAS');
export const REPOSITORIO_CONTACTOS = Symbol('REPOSITORIO_CONTACTOS');
export const REPOSITORIO_UBICACIONES = Symbol('REPOSITORIO_UBICACIONES');
